name: Build Sysex

on:
  push:
    branches:
      - rgb-feedback  # Workflow wird bei Push auf den 'rgb-feedback'-Branch ausgelöst
    tags:
      - "build_*"
      - "r_*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt install gcc-arm-none-eabi

      - name: Build Project
        run: make

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: cfw.syx
          path: ./build/
          if-no-files-found: warn
